apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sample
  namespace: test
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: docker-sample
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker-sample
        version: v1
    spec:
      containers:
      - name: docker-sample
        image: novinrepo:8082/docker/docker-sample:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
      terminationGracePeriodSeconds: 60