apiVersion: v1
kind: Service
metadata:
  name: docker-sample
  namespace: test
spec:
  selector:
    app: docker-sample
    version: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      name: web
      targetPort: 30214
      nodePort: 30214

